openapi: 3.0.0
info:
  title: Students API
  version: '1.0'
servers:
  - url: http://localhost:5000/api
paths:
  /students:
    get:
      summary: Get all students
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      summary: Add new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
  /students/{id}:
    get:
      summary: Get student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the student to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    put:
      summary: Update student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the student to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    delete:
      summary: Delete student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the student to delete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int64
        full_name:
          type: string
        subject:
          type: string
        semester:
          type: integer
          format: int32
        mark:
          type: integer
          format: int32
        year_of_study:
          type: integer
          format: int32
        age:
          type: integer
          format: int32
      required:
        - full_name
        - subject
        - semester
        - mark
        - year_of_study
        - age
